// <auto-generated />
using System;
using Entities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006044533_AddUserEmailUniqueIndex")]
    partial class AddUserEmailUniqueIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Modules.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_name")
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Korea"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Palestinian Territory"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            Name = "Egypt"
                        });
                });

            modelBuilder.Entity("Entities.Modules.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("country_id");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("name");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit")
                        .HasColumnName("receive_news_letters");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_users_country_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Address = "서울특별시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DateOfBirth = new DateTime(1989, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test1@mail.com",
                            Gender = "Female",
                            Name = "김아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Address = "경기도 안성시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DateOfBirth = new DateTime(1990, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test2@mail.com",
                            Gender = "Female",
                            Name = "최아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Address = "부산광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DateOfBirth = new DateTime(1995, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test3@mail.com",
                            Gender = "Male",
                            Name = "박아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Address = "경기도 수원시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1987, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test4@mail.com",
                            Gender = "Male",
                            Name = "우아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            Address = "강원도 춘천시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DateOfBirth = new DateTime(1995, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test5@mail.com",
                            Gender = "Female",
                            Name = "강아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            Address = "인천광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            DateOfBirth = new DateTime(1988, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test6@mail.com",
                            Gender = "Male",
                            Name = "오아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            Address = "충청북도 청주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1983, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test7@mail.com",
                            Gender = "Male",
                            Name = "연아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            Address = "대구광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1998, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test8@mail.com",
                            Gender = "Female",
                            Name = "유아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            Address = "전라북도 전주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1990, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test9@mail.com",
                            Gender = "Male",
                            Name = "한아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            Address = "경상남도 창원시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            DateOfBirth = new DateTime(1997, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test10@mail.com",
                            Gender = "Male",
                            Name = "이아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000011"),
                            Address = "광주광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DateOfBirth = new DateTime(1990, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test11@mail.com",
                            Gender = "Female",
                            Name = "차아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000012"),
                            Address = "제주특별자치도 제주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DateOfBirth = new DateTime(1987, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test12@mail.com",
                            Gender = "Female",
                            Name = "초아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000013"),
                            Address = "제주특별자치도 서귀포시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            DateOfBirth = new DateTime(2000, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test13@mail.com",
                            Gender = "Male",
                            Name = "차아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000014"),
                            Address = "울산광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1997, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test14@mail.com",
                            Gender = "Male",
                            Name = "도아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000015"),
                            Address = "충청남도 천안시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000023"),
                            DateOfBirth = new DateTime(1999, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test15@mail.com",
                            Gender = "Female",
                            Name = "배아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000016"),
                            Address = "제주특별자치도 제주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000006"),
                            DateOfBirth = new DateTime(1994, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test16@mail.com",
                            Gender = "Female",
                            Name = "김아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000017"),
                            Address = "인천광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000013"),
                            DateOfBirth = new DateTime(1988, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test17@mail.com",
                            Gender = "Male",
                            Name = "채아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000018"),
                            Address = "인천광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000018"),
                            DateOfBirth = new DateTime(1991, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test18@mail.com",
                            Gender = "Female",
                            Name = "강아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000019"),
                            Address = "경기도 용인시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000020"),
                            DateOfBirth = new DateTime(1992, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test19@mail.com",
                            Gender = "Female",
                            Name = "우아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000020"),
                            Address = "대구광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            DateOfBirth = new DateTime(2002, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test20@mail.com",
                            Gender = "Male",
                            Name = "봉아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000021"),
                            Address = "대전광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000012"),
                            DateOfBirth = new DateTime(1983, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test21@mail.com",
                            Gender = "Female",
                            Name = "설아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000022"),
                            Address = "경상북도 포항시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000020"),
                            DateOfBirth = new DateTime(1986, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test22@mail.com",
                            Gender = "Female",
                            Name = "황아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000023"),
                            Address = "경상북도 포항시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000030"),
                            DateOfBirth = new DateTime(1987, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test23@mail.com",
                            Gender = "Male",
                            Name = "현아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000024"),
                            Address = "경기도 고양시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DateOfBirth = new DateTime(1987, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test24@mail.com",
                            Gender = "Male",
                            Name = "윤아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000025"),
                            Address = "경기도 안성시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000016"),
                            DateOfBirth = new DateTime(1982, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test25@mail.com",
                            Gender = "Male",
                            Name = "진아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000026"),
                            Address = "충청남도 천안시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000024"),
                            DateOfBirth = new DateTime(2000, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test26@mail.com",
                            Gender = "Male",
                            Name = "곽아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000027"),
                            Address = "충청북도 청주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            DateOfBirth = new DateTime(1998, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test27@mail.com",
                            Gender = "Male",
                            Name = "염아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000028"),
                            Address = "경기도 파주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000022"),
                            DateOfBirth = new DateTime(1981, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test28@mail.com",
                            Gender = "Male",
                            Name = "편아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000029"),
                            Address = "서울특별시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000018"),
                            DateOfBirth = new DateTime(1992, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test29@mail.com",
                            Gender = "Female",
                            Name = "마아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000030"),
                            Address = "인천광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            DateOfBirth = new DateTime(1983, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test30@mail.com",
                            Gender = "Female",
                            Name = "성아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000031"),
                            Address = "대전광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000025"),
                            DateOfBirth = new DateTime(1985, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test31@mail.com",
                            Gender = "Other",
                            Name = "곽아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000032"),
                            Address = "광주광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000007"),
                            DateOfBirth = new DateTime(1983, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test32@mail.com",
                            Gender = "Female",
                            Name = "용아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000033"),
                            Address = "경기도 고양시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000020"),
                            DateOfBirth = new DateTime(1985, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test33@mail.com",
                            Gender = "Other",
                            Name = "왕아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000034"),
                            Address = "전라북도 전주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DateOfBirth = new DateTime(1983, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test34@mail.com",
                            Gender = "Male",
                            Name = "민아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000035"),
                            Address = "광주광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000018"),
                            DateOfBirth = new DateTime(1982, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test35@mail.com",
                            Gender = "Other",
                            Name = "장아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000036"),
                            Address = "경기도 파주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000020"),
                            DateOfBirth = new DateTime(1995, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test36@mail.com",
                            Gender = "Female",
                            Name = "곽아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000037"),
                            Address = "경상남도 창원시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000013"),
                            DateOfBirth = new DateTime(1997, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test37@mail.com",
                            Gender = "Female",
                            Name = "배아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000038"),
                            Address = "경기도 고양시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1994, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test38@mail.com",
                            Gender = "Male",
                            Name = "황아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000039"),
                            Address = "경상북도 포항시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000023"),
                            DateOfBirth = new DateTime(1997, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test39@mail.com",
                            Gender = "Male",
                            Name = "유아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000040"),
                            Address = "경기도 수원시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DateOfBirth = new DateTime(1982, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test40@mail.com",
                            Gender = "Male",
                            Name = "엄아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000041"),
                            Address = "강원도 강릉시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DateOfBirth = new DateTime(1986, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test41@mail.com",
                            Gender = "Female",
                            Name = "제아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000042"),
                            Address = "경기도 파주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000014"),
                            DateOfBirth = new DateTime(1986, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test42@mail.com",
                            Gender = "Male",
                            Name = "봉아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000043"),
                            Address = "제주특별자치도 서귀포시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000013"),
                            DateOfBirth = new DateTime(1981, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test43@mail.com",
                            Gender = "Male",
                            Name = "예아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000044"),
                            Address = "경기도 파주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            DateOfBirth = new DateTime(1983, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test44@mail.com",
                            Gender = "Female",
                            Name = "손아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000045"),
                            Address = "충청남도 천안시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000028"),
                            DateOfBirth = new DateTime(1994, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test45@mail.com",
                            Gender = "Male",
                            Name = "임아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000046"),
                            Address = "세종특별자치시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000030"),
                            DateOfBirth = new DateTime(2000, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test46@mail.com",
                            Gender = "Other",
                            Name = "이아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000047"),
                            Address = "경기도 안성시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000006"),
                            DateOfBirth = new DateTime(1995, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test47@mail.com",
                            Gender = "Other",
                            Name = "염아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000048"),
                            Address = "제주특별자치도 서귀포시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000023"),
                            DateOfBirth = new DateTime(1992, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test48@mail.com",
                            Gender = "Male",
                            Name = "설아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000049"),
                            Address = "울산광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            DateOfBirth = new DateTime(1997, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test49@mail.com",
                            Gender = "Male",
                            Name = "위아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000050"),
                            Address = "부산광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DateOfBirth = new DateTime(1998, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test50@mail.com",
                            Gender = "Female",
                            Name = "윤아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000051"),
                            Address = "대전광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1996, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test51@mail.com",
                            Gender = "Other",
                            Name = "윤아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000052"),
                            Address = "전라북도 전주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000029"),
                            DateOfBirth = new DateTime(1982, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test52@mail.com",
                            Gender = "Male",
                            Name = "심아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000053"),
                            Address = "전라북도 전주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000019"),
                            DateOfBirth = new DateTime(1999, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test53@mail.com",
                            Gender = "Male",
                            Name = "한아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000054"),
                            Address = "광주광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000013"),
                            DateOfBirth = new DateTime(1988, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test54@mail.com",
                            Gender = "Male",
                            Name = "진아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000055"),
                            Address = "전라북도 전주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000020"),
                            DateOfBirth = new DateTime(1989, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test55@mail.com",
                            Gender = "Male",
                            Name = "임아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000056"),
                            Address = "경기도 용인시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000030"),
                            DateOfBirth = new DateTime(1982, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test56@mail.com",
                            Gender = "Male",
                            Name = "명아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000057"),
                            Address = "제주특별자치도 제주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000018"),
                            DateOfBirth = new DateTime(1987, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test57@mail.com",
                            Gender = "Male",
                            Name = "홍아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000058"),
                            Address = "경상남도 창원시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            DateOfBirth = new DateTime(2000, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test58@mail.com",
                            Gender = "Female",
                            Name = "사아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000059"),
                            Address = "경기도 수원시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            DateOfBirth = new DateTime(1984, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test59@mail.com",
                            Gender = "Female",
                            Name = "신아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000060"),
                            Address = "경기도 수원시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000028"),
                            DateOfBirth = new DateTime(1986, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test60@mail.com",
                            Gender = "Female",
                            Name = "백아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000061"),
                            Address = "부산광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000009"),
                            DateOfBirth = new DateTime(1988, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test61@mail.com",
                            Gender = "Male",
                            Name = "용아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000062"),
                            Address = "제주특별자치도 제주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000018"),
                            DateOfBirth = new DateTime(1984, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test62@mail.com",
                            Gender = "Female",
                            Name = "홍아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000063"),
                            Address = "부산광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000018"),
                            DateOfBirth = new DateTime(1980, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test63@mail.com",
                            Gender = "Other",
                            Name = "보아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000064"),
                            Address = "경기도 용인시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            DateOfBirth = new DateTime(1998, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test64@mail.com",
                            Gender = "Male",
                            Name = "소아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000065"),
                            Address = "경기도 용인시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            DateOfBirth = new DateTime(1981, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test65@mail.com",
                            Gender = "Male",
                            Name = "황아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000066"),
                            Address = "대전광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DateOfBirth = new DateTime(1993, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test66@mail.com",
                            Gender = "Other",
                            Name = "전아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000067"),
                            Address = "경기도 파주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            DateOfBirth = new DateTime(1985, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test67@mail.com",
                            Gender = "Female",
                            Name = "문아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000068"),
                            Address = "강원도 강릉시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DateOfBirth = new DateTime(1987, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test68@mail.com",
                            Gender = "Male",
                            Name = "신아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000069"),
                            Address = "울산광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000022"),
                            DateOfBirth = new DateTime(1994, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test69@mail.com",
                            Gender = "Male",
                            Name = "남아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000070"),
                            Address = "경기도 안성시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000017"),
                            DateOfBirth = new DateTime(1988, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test70@mail.com",
                            Gender = "Male",
                            Name = "차아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000071"),
                            Address = "대전광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000009"),
                            DateOfBirth = new DateTime(1997, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test71@mail.com",
                            Gender = "Female",
                            Name = "권아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000072"),
                            Address = "경기도 고양시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000024"),
                            DateOfBirth = new DateTime(1988, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test72@mail.com",
                            Gender = "Male",
                            Name = "탁아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000073"),
                            Address = "제주특별자치도 제주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DateOfBirth = new DateTime(1996, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test73@mail.com",
                            Gender = "Male",
                            Name = "제아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000074"),
                            Address = "대구광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000014"),
                            DateOfBirth = new DateTime(1996, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test74@mail.com",
                            Gender = "Male",
                            Name = "사아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000075"),
                            Address = "경기도 성남시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000024"),
                            DateOfBirth = new DateTime(1990, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test75@mail.com",
                            Gender = "Female",
                            Name = "봉아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000076"),
                            Address = "광주광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000018"),
                            DateOfBirth = new DateTime(2001, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test76@mail.com",
                            Gender = "Female",
                            Name = "염아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000077"),
                            Address = "경기도 안성시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000010"),
                            DateOfBirth = new DateTime(2001, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test77@mail.com",
                            Gender = "Female",
                            Name = "문아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000078"),
                            Address = "전라남도 목포시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000019"),
                            DateOfBirth = new DateTime(1980, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test78@mail.com",
                            Gender = "Male",
                            Name = "백아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000079"),
                            Address = "제주특별자치도 서귀포시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000016"),
                            DateOfBirth = new DateTime(1994, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test79@mail.com",
                            Gender = "Male",
                            Name = "부아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000080"),
                            Address = "대구광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            DateOfBirth = new DateTime(1982, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test80@mail.com",
                            Gender = "Female",
                            Name = "봉아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000081"),
                            Address = "서울특별시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            DateOfBirth = new DateTime(1987, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test81@mail.com",
                            Gender = "Female",
                            Name = "유아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000082"),
                            Address = "경상북도 포항시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000029"),
                            DateOfBirth = new DateTime(1995, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test82@mail.com",
                            Gender = "Female",
                            Name = "임아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000083"),
                            Address = "경상북도 포항시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000005"),
                            DateOfBirth = new DateTime(2002, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test83@mail.com",
                            Gender = "Male",
                            Name = "표아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000084"),
                            Address = "충청북도 청주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000023"),
                            DateOfBirth = new DateTime(1983, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test84@mail.com",
                            Gender = "Female",
                            Name = "문아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000085"),
                            Address = "강원도 춘천시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000026"),
                            DateOfBirth = new DateTime(1997, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test85@mail.com",
                            Gender = "Female",
                            Name = "황아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000086"),
                            Address = "충청북도 청주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000024"),
                            DateOfBirth = new DateTime(1997, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test86@mail.com",
                            Gender = "Female",
                            Name = "석아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000087"),
                            Address = "세종특별자치시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000025"),
                            DateOfBirth = new DateTime(1997, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test87@mail.com",
                            Gender = "Female",
                            Name = "길아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000088"),
                            Address = "대구광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000015"),
                            DateOfBirth = new DateTime(1988, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test88@mail.com",
                            Gender = "Male",
                            Name = "편아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000089"),
                            Address = "광주광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1987, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test89@mail.com",
                            Gender = "Female",
                            Name = "진아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000090"),
                            Address = "경기도 고양시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000014"),
                            DateOfBirth = new DateTime(1992, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test90@mail.com",
                            Gender = "Male",
                            Name = "허아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000091"),
                            Address = "전라북도 전주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000025"),
                            DateOfBirth = new DateTime(1993, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test91@mail.com",
                            Gender = "Male",
                            Name = "추아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000092"),
                            Address = "경기도 성남시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000012"),
                            DateOfBirth = new DateTime(1980, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test92@mail.com",
                            Gender = "Male",
                            Name = "연아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000093"),
                            Address = "세종특별자치시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000029"),
                            DateOfBirth = new DateTime(1993, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test93@mail.com",
                            Gender = "Female",
                            Name = "옥아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000094"),
                            Address = "경상남도 창원시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000022"),
                            DateOfBirth = new DateTime(1988, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test94@mail.com",
                            Gender = "Male",
                            Name = "최아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000095"),
                            Address = "경기도 안성시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000030"),
                            DateOfBirth = new DateTime(1985, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test95@mail.com",
                            Gender = "Female",
                            Name = "은아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000096"),
                            Address = "강원도 춘천시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000028"),
                            DateOfBirth = new DateTime(2001, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test96@mail.com",
                            Gender = "Male",
                            Name = "예아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000097"),
                            Address = "경기도 안성시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000011"),
                            DateOfBirth = new DateTime(1988, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test97@mail.com",
                            Gender = "Female",
                            Name = "허아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000098"),
                            Address = "충청남도 천안시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000024"),
                            DateOfBirth = new DateTime(1993, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test98@mail.com",
                            Gender = "Female",
                            Name = "한아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000099"),
                            Address = "부산광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000021"),
                            DateOfBirth = new DateTime(1991, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test99@mail.com",
                            Gender = "Female",
                            Name = "장아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000100"),
                            Address = "광주광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DateOfBirth = new DateTime(1987, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test100@mail.com",
                            Gender = "Female",
                            Name = "박아무개",
                            ReceiveNewsLetters = true
                        });
                });

            modelBuilder.Entity("Entities.Modules.Users.User", b =>
                {
                    b.HasOne("Entities.Modules.Countries.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .HasConstraintName("fk_users_countries_country_id");

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
