// <auto-generated />
using System;
using Entities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Modules.Countries.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_name")
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Korea"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Palestinian Territory"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Denmark"
                        });
                });

            modelBuilder.Entity("Entities.Modules.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("country_id");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("name");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit")
                        .HasColumnName("receive_news_letters");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_users_country_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Address = "서울특별시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DateOfBirth = new DateTime(1989, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test1@mail.com",
                            Gender = "Female",
                            Name = "김아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Address = "경기도 안성시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DateOfBirth = new DateTime(1990, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test2@mail.com",
                            Gender = "Female",
                            Name = "최아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Address = "부산광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DateOfBirth = new DateTime(1995, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test3@mail.com",
                            Gender = "Male",
                            Name = "박아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Address = "경기도 수원시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1987, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test4@mail.com",
                            Gender = "Male",
                            Name = "우아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            Address = "강원도 춘천시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DateOfBirth = new DateTime(1995, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test5@mail.com",
                            Gender = "Gender",
                            Name = "강아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            Address = "인천광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            DateOfBirth = new DateTime(1988, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test6@mail.com",
                            Gender = "Male",
                            Name = "오아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            Address = "충청북도 청주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1983, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test7@mail.com",
                            Gender = "Male",
                            Name = "연아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            Address = "대구광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1998, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test8@mail.com",
                            Gender = "Female",
                            Name = "유아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            Address = "전라북도 전주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(1990, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test9@mail.com",
                            Gender = "Male",
                            Name = "한아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            Address = "경상남도 창원시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000004"),
                            DateOfBirth = new DateTime(1997, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test10@mail.com",
                            Gender = "Male",
                            Name = "이아무개",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000011"),
                            Address = "광주광역시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DateOfBirth = new DateTime(1990, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test11@mail.com",
                            Gender = "Female",
                            Name = "차아무개",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000012"),
                            Address = "제주특별자치도 제주시",
                            CountryId = new Guid("00000000-0000-0000-0000-000000000008"),
                            DateOfBirth = new DateTime(1987, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test12@mail.com",
                            Gender = "Female",
                            Name = "초아무개",
                            ReceiveNewsLetters = true
                        });
                });

            modelBuilder.Entity("Entities.Modules.Users.User", b =>
                {
                    b.HasOne("Entities.Modules.Countries.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .HasConstraintName("fk_users_countries_country_id");

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
