<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3f1da0da-fa27-4cba-9ced-46f5376e2240</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ServiceContracts/ServiceContracts.csproj" />
    <ProjectReference Include="../Services/Services.csproj" />
  </ItemGroup>

</Project>
